name: "Publish Foundation NuGet Packages : Back-End (Main)"

on:
  push:
    paths:
      - "BE/Base/Foundation/**"
    branches: 
      - main
    tags:
      - foundation-*

env:
  DOTNET_SDK_VERSION: "8.0.100"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}    

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
          additionalArguments: '/showConfig'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('BE/Base/Foundation/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: |
          cd BE/Base/Foundation/Apis
          dotnet restore Foundation.Apis.csproj 

      - name: Build project
        run: |
          cd BE/Base/Foundation/Apis
          dotnet build Foundation.Apis.csproj --no-incremental -c Release /p:Version=${{ steps.gitversion.outputs.semVer }} /p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} /p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }}

      - name: Pack project
        run: |
          cd BE/Base/Foundation/Apis
          dotnet pack Foundation.Apis.csproj -c Release --no-build /p:Version=${{ steps.gitversion.outputs.semVer }}

      - name: Authenticate with NuGet
        run: dotnet nuget add source https://nuget.pkg.github.com/jalbarranelectronic/index.json --name github --username 'jalbarranelectronic' --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

      - name: Publish NuGet package
        run: |
          cd BE/Base/Foundation/Apis
          dotnet nuget push bin/Release/*.nupkg --source https://nuget.pkg.github.com/jalbarranelectronic/index.json
