name: "Publish Foundation NuGet Packages : Back-End (Main)"

on:
  push:
    tags:
      - foundation-*

env:
  DOTNET_SDK_VERSION: "8.0.100"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}    

      - name: Get version from tag
        id: release_info
        uses: revam/gh-action-get-tag-and-version@v1
        with:
          tag: ${{ github.ref }}
          prefixRegex: "foundation-"

      - name: Restore dependencies on Foundation solution
        run: |
          cd BE
          dotnet restore TestGitHubActions.Foundation.sln 

      - name: Build Foundation solution
        run: |
          cd BE
          dotnet build TestGitHubActions.Foundation.sln  --no-incremental -c Release /p:Version=${{ steps.release_info.outputs.version_short }}

      - name: Pack Foundation solution
        run: |
          cd BE
          dotnet pack TestGitHubActions.Foundation.sln -c Release --no-build /p:Version=${{ steps.release_info.outputs.version_short }}

      - name: Authenticate with NuGet
        run: dotnet nuget add source https://nuget.pkg.github.com/jalbarranelectronic/index.json --name github --username 'jalbarranelectronic' --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

      - name: Publish NuGet packages
        run: |
          cd BE
          dotnet nuget push BE/Base/Foundation/**/*.nupkg --source https://nuget.pkg.github.com/jalbarranelectronic/index.json
